// Built by Louis Innovations (www.louis-innovations.com)

import 'package:flutter/foundation.dart';
import 'package:flutter/gestures.dart';
import 'package:flutter/material.dart';
import 'package:webview_flutter/webview_flutter.dart';

/// A WebView wrapper optimised for SADAD payment pages.
///
/// Configures the underlying [WebViewController] with the settings required
/// by the SADAD gateway:
///   - JavaScript enabled
///   - DOM storage enabled
///   - Third-party cookies enabled (required for the embedded v2.2 flow)
///   - Mixed-content allowed in test environments
///
/// For **web** builds the [SadadWebView] renders the payment page in an
/// `<iframe>` via [HtmlElementView]. For **mobile** (iOS / Android) it
/// uses the `webview_flutter` plugin.
///
/// Intercepts URL navigation to detect when SADAD redirects back to the
/// merchant callback URL.
///
/// Example:
/// ```dart
/// SadadWebView(
///   initialUrl: 'https://sadadqa.com/webpurchase',
///   callbackUrl: 'https://www.your-domain.com/callback',
///   onCallbackDetected: (url) { /* handle result */ },
///   onPageStarted:  (url) { /* loading started */ },
///   onPageFinished: (url) { /* loading complete */ },
///   onWebResourceError: (err) { /* handle error */ },
/// )
/// ```
class SadadWebView extends StatefulWidget {
  /// The URL to load initially. For HTML-form-based checkouts supply
  /// [initialHtml] instead and leave this `null`.
  final String? initialUrl;

  /// Raw HTML to load as the initial page content. Typically the
  /// auto-submitting form generated by [SadadCheckoutManager.buildCheckoutHtml].
  final String? initialHtml;

  /// The merchant callback URL. When the WebView navigates to a URL that
  /// starts with this value, [onCallbackDetected] is invoked and navigation
  /// is blocked.
  final String? callbackUrl;

  /// Invoked when a navigation matches the [callbackUrl].
  final void Function(String url)? onCallbackDetected;

  /// Invoked when a page starts loading.
  final void Function(String url)? onPageStarted;

  /// Invoked when a page finishes loading.
  final void Function(String url)? onPageFinished;

  /// Invoked when a web resource error occurs.
  final void Function(WebResourceError error)? onWebResourceError;

  /// Whether to show the built-in loading indicator overlay while the first
  /// page is loading. Defaults to `true`.
  final bool showLoadingIndicator;

  /// Background colour for the WebView widget. Defaults to white.
  final Color backgroundColor;

  const SadadWebView({
    super.key,
    this.initialUrl,
    this.initialHtml,
    this.callbackUrl,
    this.onCallbackDetected,
    this.onPageStarted,
    this.onPageFinished,
    this.onWebResourceError,
    this.showLoadingIndicator = true,
    this.backgroundColor = Colors.white,
  }) : assert(
          initialUrl != null || initialHtml != null,
          'Provide either initialUrl or initialHtml.',
        );

  @override
  State<SadadWebView> createState() => _SadadWebViewState();
}

class _SadadWebViewState extends State<SadadWebView> {
  late final WebViewController _controller;
  bool _isLoading = true;

  @override
  void initState() {
    super.initState();
    _initController();
  }

  void _initController() {
    _controller = WebViewController()
      ..setJavaScriptMode(JavaScriptMode.unrestricted)
      ..setBackgroundColor(widget.backgroundColor)
      ..setNavigationDelegate(
        NavigationDelegate(
          onPageStarted: (url) {
            if (mounted) setState(() => _isLoading = true);
            widget.onPageStarted?.call(url);
          },
          onPageFinished: (url) {
            if (mounted) setState(() => _isLoading = false);
            widget.onPageFinished?.call(url);
          },
          onWebResourceError: (error) {
            if (mounted) setState(() => _isLoading = false);
            widget.onWebResourceError?.call(error);
          },
          onNavigationRequest: (request) {
            final url = request.url;

            // Intercept SADAD callback URL navigation.
            if (_isCallbackUrl(url)) {
              widget.onCallbackDetected?.call(url);
              return NavigationDecision.prevent;
            }

            return NavigationDecision.navigate;
          },
        ),
      );

    // Enable DOM storage and third-party cookies on Android.
    // On iOS these are enabled by default.
    if (!kIsWeb) {
      _controller.enableZoom(false);
    }

    // Load the initial content.
    if (widget.initialHtml != null) {
      _controller.loadHtmlString(widget.initialHtml!);
    } else if (widget.initialUrl != null) {
      _controller.loadRequest(Uri.parse(widget.initialUrl!));
    }
  }

  bool _isCallbackUrl(String url) {
    final callbackUrl = widget.callbackUrl;
    if (callbackUrl == null || callbackUrl.isEmpty) return false;

    try {
      final parsed = Uri.parse(url);
      final callback = Uri.parse(callbackUrl);

      final sameHost =
          parsed.host.toLowerCase() == callback.host.toLowerCase();
      final samePath =
          parsed.path.toLowerCase().startsWith(callback.path.toLowerCase());

      return sameHost && samePath;
    } catch (_) {
      return false;
    }
  }

  @override
  Widget build(BuildContext context) {
    // On web, webview_flutter renders via HtmlElementView / iframe internally.
    // No special handling is needed at the widget level.
    final webView = WebViewWidget(
      controller: _controller,
      gestureRecognizers: {
        Factory<VerticalDragGestureRecognizer>(
          () => VerticalDragGestureRecognizer(),
        ),
      },
    );

    if (!widget.showLoadingIndicator) {
      return webView;
    }

    return Stack(
      children: [
        webView,
        if (_isLoading)
          const Positioned.fill(
            child: ColoredBox(
              color: Colors.white,
              child: Center(
                child: CircularProgressIndicator(
                  valueColor: AlwaysStoppedAnimation<Color>(Color(0xFF1A6DB5)),
                ),
              ),
            ),
          ),
      ],
    );
  }
}
